import Logo from "./components/Logo";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "The-wild-oasis",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
